name: Add input

on:
  repository_dispatch:
    types: [add-input]

jobs:
  add-input:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - run: bun install

    - name: Run script
      id: script
      env:
        URL: ${{ github.event.client_payload.url }}
      run: |
        content=$(bun scripts/add-input.ts "${{ github.event.client_payload.url }}")
        echo "content=$content" >> $GITHUB_OUTPUT

    - name: Update file
      run: |
        echo -e "${{ steps.script.outputs.content }}\n$(cat ./Inputs.md)" > temp
        mv -f temp ./Inputs.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add ./Inputs.md
        git commit -m "Add Input by GitHub Actions"
        git push
