name: Add input

on:
  repository_dispatch:
    types: [add-input]

jobs:
  add-input:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-

    - name: Install dependencies
      run: bun install

    - name: Install Chrome
      run: bunx @puppeteer/browsers install chrome@stable --path ${{ github.workspace }}/node_modules/@puppeteer

    - name: Run script
      id: script
      env:
        URL: ${{ github.event.client_payload.url }}
      run: |
        content=$(bun scripts/add-input.ts "${{ github.event.client_payload.url }}")
        echo "content=$content" >> $GITHUB_OUTPUT

    - name: Update file
      run: |
        printf "%s\n%s" "${{ steps.script.outputs.content }}" "$(cat ./Inputs.md)" > temp
        mv -f temp ./Inputs.md

    - name: Commit and push changes
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add ./Inputs.md
        git commit -m "Add Input by GitHub Actions"
        git push
