name: Add input

on:
  push:
    branches:
      - main
    paths:
      - inputs.json

jobs:
  add-input:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/bun.lockb') }}

    - name: Install dependencies
      run: |
        bun --filter=add-inputs install
        bun --filter=add-inputs install:chrome

    - name: Run script and Update file
      run: |
        bun apps/add-inputs/src/json-to-md.ts
